In [ ]:
from sklearn.datasets import load_wine

In [ ]:
import pandas as pd

data_wine = load_wine()

wine_df= pd.DataFrame(data_wine.data, columns = data_wine.feature_names)
target_df = pd.DataFrame(data_wine.target, columns=['target'])

In [ ]:
wine_df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [ ]:
wine_df.iloc[0].values

array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03])

In [ ]:
wine_df.iloc[1].values

array([1.32e+01, 1.78e+00, 2.14e+00, 1.12e+01, 1.00e+02, 2.65e+00,
       2.76e+00, 2.60e-01, 1.28e+00, 4.38e+00, 1.05e+00, 3.40e+00,
       1.05e+03])

In [ ]:
# np.sum(wine_df.iloc[0].values * wine_df.iloc[1].values)
# = np.dot(wine_df.iloc[0].values, wine_df.iloc[1].values)
np.dot(wine_df.iloc[0].values, wine_df.iloc[1].values) / \
(np.sum(wine_df.iloc[0].values ** 2)**0.5 * np.sum(wine_df.iloc[1].values**2) *0.5 )

0.0018953275920695577

In [ ]:
# np.sum(wine_df.iloc[0].values ** 2)**0.5  밑에 식이랑 같음
np.linalg.norm(wine_df.iloc[0].values)

1072.79050405939

In [ ]:
import numpy as np

def euclidean_distance(a:np.array, b:np.array):
    dist = 0
    # 계산
    # x1-y1 제곱 + x2-y2 제곱 + x3-y3 제곱 + ... + xn-yn 제곱 -> sqrt

    return np.sum((a-b)**2)**0.5

def cosine_similarity(a:np.array, b:np.array):
    similarity = 0
    # 계산
    similarity = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
    # ab 내적 / (a크기 * b크기)
    return similarity

In [ ]:
result_dist = []
result_sim = []
# result[0] => 0번째 index 데이터를 기준으로 0~177 각각 dist 계산한 값들이 들어가야됩니다
# result[0] = [0, 0.3, 0.7, ... 177]
# result[1] = [0.3, 0, ... , ]

for i in range(len(wine_df)): # 기준 데이터
    temp_dist = []
    temp_sim = []
    for j in range(len(wine_df)): # 비교대상
        base_point = wine_df.iloc[i].values
        target_point = wine_df.iloc[j].values
        # distance 계산
        dist = euclidean_distance(base_point, target_point)
        temp_dist.append(dist)
        # similarity 계산
        simm = cosine_similarity(base_point, target_point)
        temp_sim.append(simm)

    result_dist.append(temp_dist)
    result_sim.append(temp_sim)

In [ ]:
len(dist_result[0])

178

In [ ]:
target_item = 0
k = 10
pd.DataFrame(result_dist)[target_item].sort_values()[1:k+1] #  -> 자기와 가까운 데이터 순, 0번째는 자기 자신이여서 값이 0

54    10.392805
45    22.340748
48    24.760232
46    25.094663
1     31.265012
34    34.718304
9     35.274977
8     36.116966
42    39.718415
22    39.763341
Name: 0, dtype: float64

In [ ]:
target_item = 10
k = 10
pd.DataFrame(result_sim)[target_item].sort_values(ascending=False)[:k]

10    1.000000
31    0.999999
12    0.999997
27    0.999992
11    0.999987
6     0.999986
51    0.999986
14    0.999984
18    0.999982
3     0.999975
Name: 10, dtype: float64

In [ ]:
target_df

     target
0         0
1         0
2         0
3         0
4         0
..      ...
173       2
174       2
175       2
176       2
177       2

[178 rows x 1 columns]

In [ ]:
# 거리, 유사도 계산한 것을 어떻게 활용?
# 나와 거리가 가까운 데이터를 찾는데 활용가능
# 나와 유사도의 정도를 확인할 때 활용가능